name: first workflow
env:
 WORKFLOW_VAR: "This variable is declared at the workflow level"
 
on:
  workflow_dispatch:
  
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: firstjob script
        shell: bash
        run: echo Hello World!
      - name: checkout
        uses: actions/checkout@v3
      - name: greetings
        id: greetings
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Mona the Octocat'
      - name: time
        run: |
          echo "The time of the greeting was at: ${{ steps.greetings.outputs.time }}"
  
  secondjob:
    runs-on: ubuntu-latest
    needs: firstjob
    env:
      JOB_VAR: " This is a job variable"
    steps:
      - name: environment variables
        env:
          STEP_VAR: "This variable is declared at the step level"
      - name: secondJob script
        shell: bash
        run: |
         echo $WORKFLOW_VAR
         echo $JOB_VAR
         echo $STEP_VAR
         echo "The following is a secret: ${{ secrets.SOME_SECRET }}, of course, I cant tell you because then it wouldnt be a secret..."
         echo "The following are default environment variables:"
         echo $GITHUB_ACTOR
         echo $GITHUB_JOB
         echo $GITHUB_REF
